development:
  adapter: postgresql
  encoding: unicode
  database: SBTR_development
  host: localhost
  min_messages: warning
test:
  adapter: postgresql
  encoding: unicode
  database: SBTR_test
  host: localhost
  min_messages: warning
